Import( '*' )

# environment
env.VariantDir( build_dir, '#', duplicate = 0 )
client_env = env.Clone()

# sources
files = [
	'XSClient/XSBaseCamera.cpp',
	'XSClient/XSClientGame.cpp',
	'XSClient/XSClientGameState.cpp',
	'XSClient/XSFlyCamera.cpp',
	'XSClient/XSEntity.cpp',
	'XSClient/XSEntityFXRunner.cpp',
	'XSClient/XSEntityModel.cpp',
	'XSClient/XSMenu.cpp',
	'XSClient/XSMenuElement.cpp',
	'XSClient/XSMenuElementButton.cpp',
	'XSClient/XSMenuElementSlider.cpp',
	'XSClient/XSMenuElementText.cpp',
	'XSClient/XSMenuManager.cpp',
	'XSClient/XSParticleEmitter.cpp',
	'XSClient/XSPerlin.cpp',
	'XSClient/XSResources.cpp',
	'XSClient/XSTerrain.cpp'
]
files = [build_dir + f for f in files]

# targets
result = client_env.StaticLibrary( build_dir + 'XSClient' + arch, files )
Return( "result" )
