Import( '*' )

# environment
env.VariantDir( build_dir, '#', duplicate = 0 )
server_env = env.Clone()

# sources
files = [
	'XSServer/XSCharacter.cpp',
	'XSServer/XSClient.cpp',
	'XSServer/XSEntity.cpp',
	'XSServer/XSEntityFXRunner.cpp',
	'XSServer/XSEntityModel.cpp',
	'XSServer/XSInventoryManager.cpp',
	'XSServer/XSNetcode.cpp',
	'XSServer/XSQuest.cpp',
	'XSServer/XSQuestManager.cpp',
	'XSServer/XSResources.cpp',
	'XSServer/XSServerGame.cpp',
]
files = [build_dir + f for f in files]

# targets
result = server_env.StaticLibrary( build_dir + 'XSServer' + arch, files )
Return( "result" )
